language: node_js
node_js:
- '16'
sudo: required
services:
- docker
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: fzcam4FZsDfMPV6tC8seaC/SRXhSXDyC8kPjYhrWxgXu7vsfw5yDXtVpaZ64PpvqHVvxYajep/IuMv42EaCkz3VIcor3v6xdCZFpZgMZAA5yNajGAKg3vbrczfhUXcyie39c2MapNIf35e+DZixyNhJVsd542d6q47xciotnPyS5bewJqSNaHThzUGUZzXyXTqg8xKqEE140fvwRwEIHx/qg00Q1Kyw9r6It8Kydlg+zh4Z7AXdRpn8yGvOmjyOKE3f3imXlxMdycwPGEkT3EAwAPqupSplpnD3euPwaJYEDJAPQXAU7a67LnDHY7tAT7khkDITbFs06IklCT9gzLVp3Z/TeMTa1nemA+kwk8iErXIwYolT8CdtZ8A/MUYvpDZ1q5rGiqwA0vu3aqfU3WESYw8s0jsnQRJnFvfOz2943l0FEfaQmKcAml1JM0eMbM0LDLTHYGu4/F0ip5IZGrKT7l/k/lT+tO1VHdxKhbX3R3MwmYBCAhpRGhszgC/BnfZPkPbR6HvpCTnL9bWV7A9TsQhG1KEjhnB5u0RMl950KjYU7gEFEgOz6eiR3ay89xMvyonQxQOXWuVRmZhvs/6YT8i4n/8KS58HDIERFWKfhbZVTe7S4KnighaZwvYONP5no+SN2y6+y7aTmpM/vHrkk3uY7Lnc47do9w63XyLY=
script:
- bash .travis.build.sh
